# Generated by Django 4.0.2 on 2022-02-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hzUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('l_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('S_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('DOB', models.DateField(verbose_name='Дата рождения')),
                ('reg_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес регистрации')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('type', models.CharField(choices=[('admin', 'Администратор'), ('doctor', 'Врач'), ('patient', 'Пациент')], default='patient', max_length=7, verbose_name='Тип пользователя')),
                ('hzuser_foto', models.FileField(blank=True, null=True, upload_to='CRM/media/CRM/foto/users/%Y/%m/%d/', verbose_name='Фотография')),
                ('hz_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация пользователей',
            },
        ),
        migrations.CreateModel(
            name='hzUserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('title', models.CharField(max_length=100, verbose_name='Событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_media', models.FileField(blank=True, null=True, upload_to='CRM/static/CRM/upload/events/', verbose_name='Медиафайлы')),
                ('hz_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Список событий',
                'ordering': ('-date_time',),
            },
        ),
    ]
