# Generated by Django 4.0.2 on 2022-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hzuserinfo',
            name='hzuser_foto',
        ),
        migrations.AddField(
            model_name='hzuserinfo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='crm/media/crm/foto/users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
