# Generated by Django 4.0.2 on 2022-02-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_hzuserinfo_hzuser_foto_hzuserinfo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hzuserinfo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media/foto/users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='hzuserinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
    ]
