# Generated by Django 4.1.1 on 2022-09-19 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_hzuserinfo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Внешний ИД')),
                ('state', models.PositiveIntegerField(verbose_name='Статус')),
                ('content', models.JSONField(verbose_name='Содержимое анкеты')),
                ('date_filling', models.DateField(default=datetime.datetime(2022, 9, 18, 5, 31, 14, 403598), verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('-external_id',),
            },
        ),
    ]
