# Generated by Django 4.1.1 on 2022-09-19 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_anket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='date_filling',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 5, 34, 9, 812084), verbose_name='Дата заполнения'),
        ),
    ]
