# Generated by Django 4.1.1 on 2022-09-28 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_anket_date_filling'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Код операции')),
                ('name', models.CharField(max_length=50, verbose_name='Название операции')),
                ('s_name', models.CharField(max_length=25, verbose_name='Сокращённое название')),
            ],
            options={
                'verbose_name': 'Вид операции',
                'verbose_name_plural': 'Виды операций',
                'ordering': ('code',),
            },
        ),
        migrations.AlterField(
            model_name='anket',
            name='date_filling',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Дата заполнения'),
        ),
    ]
